#!/usr/bin/env zsh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
OUTPUT_DIR=$HOME
FILES_TO_LINK=(
  aliases
  gitconfig
  gitignore
  ignore
  zshrc
)

DIRS_TO_LINK=(
  bin
)

autoload -U colors && colors
function print_info {
  group=$1
  message="$2"

  echo "$fg[magenta][$group]$reset_color $message"
}

function link_files {
  print_info "dotfiles" "symlinking files"
  for file in "${FILES_TO_LINK[@]}"; do
    print_info $file "linking to $OUTPUT_DIR/.$file"
    ln -sf $DIR/$file $OUTPUT_DIR/.$file
  done
}

function link_dirs {
  print_info "dotfiles" "symlinking directories"
  for dir in "${DIRS_TO_LINK[@]}"; do
    print_info $dir "linking to $OUTPUT_DIR/$dir"
    ln -sf $DIR/$dir $OUTPUT_DIR/$dir
  done
}

link_files
link_dirs
